In [2]:
import pandas as pd

df_rank = pd.read_csv('../catboost-classifier/datasets/rank_dataset_TRAIN_CATBOOST.csv')
df_mapping = pd.read_csv('./exercises_base_FINAL_CLEANED.csv')
df_profiles = pd.read_csv('./powerlifting_profiles_clean.csv')

df_stage_1 = df_rank.merge(
    df_mapping[['exercise_id', 'Base_Lift', 'Exercise_Name']], 
    left_on='candidate_id', 
    right_on='exercise_id', 
    how='inner' # Оставляем только то, что разметили и что есть в трейне
)

final_master_df = df_stage_1.join(df_profiles, how='inner')

final_master_df.to_csv('MASTER_CATBOOST_DATASET.csv', index=False)

print(f"Сборка завершена!")
print(f"Финальное количество строк: {len(final_master_df)}")
display(final_master_df.head())

Сборка завершена!
Финальное количество строк: 45239

,bert_score,candidate_id,is_same_group,target,eq_clean,level_idx,goal_clean,exercise_id,Base_Lift,Exercise_Name,Sex,Age,BodyweightKg,Best3SquatKg,Best3BenchKg,Best3DeadliftKg
0,0.001278,1546,0,0,Machine,3,Powerbuilding,1546,Best3BenchKg,Low Cable Fly,F,33.0,58.30,80.0,60.0,107.5
1,0.001276,1440,0,0,Machine,0,Bodybuilding,1440,Best3DeadliftKg,Lat Pullover,F,43.0,73.10,105.0,67.5,110.0
2,0.001778,2733,0,0,Machine,0,Athletics,2733,Best3DeadliftKg,Super ROM Overhead Cable Row,M,15.5,67.40,100.0,62.5,105.0
3,0.001300,2731,0,0,Dumbbell,0,Athletics,2731,Best3DeadliftKg,Super ROM Lateral Dumbbell Raise,M,35.0,66.65,137.5,122.5,170.0
4,0.001246,1075,0,0,Barbell,1,Athletics,1075,Best3BenchKg,Half Kneeling Landmine Press,M,26.5,72.45,90.0,50.0,125.0

In [3]:
features_with_id = [
    'exercise_id',
    'Sex', 'Age', 'BodyweightKg', 
    'eq_clean', 'level_idx', 'goal_clean', 
    'Base_Lift', 
    'Best3SquatKg', 'Best3BenchKg', 'Best3DeadliftKg'
]

df_final_reg = final_master_df[features_with_id].copy()

df_final_reg['exercise_id'] = df_final_reg['exercise_id'].astype(int)

print(f"Теперь всё на месте. Размер: {df_final_reg.shape}")
display(df_final_reg.head(20))

Теперь всё на месте. Размер: (45239, 11)

,exercise_id,Sex,Age,BodyweightKg,eq_clean,level_idx,goal_clean,Base_Lift,Best3SquatKg,Best3BenchKg,Best3DeadliftKg
0,1546,F,33.0,58.30,Machine,3,Powerbuilding,Best3BenchKg,80.0,60.0,107.5
1,1440,F,43.0,73.10,Machine,0,Bodybuilding,Best3DeadliftKg,105.0,67.5,110.0
2,2733,M,15.5,67.40,Machine,0,Athletics,Best3DeadliftKg,100.0,62.5,105.0
3,2731,M,35.0,66.65,Dumbbell,0,Athletics,Best3DeadliftKg,137.5,122.5,170.0
4,1075,M,26.5,72.45,Barbell,1,Athletics,Best3BenchKg,90.0,50.0,125.0
5,1134,M,15.5,78.80,Dumbbell,2,Powerbuilding,Best3DeadliftKg,100.0,60.0,115.0
6,2577,M,57.5,79.65,Dumbbell,2,Powerlifting,Best3DeadliftKg,180.0,100.0,55.0
7,185,F,26.0,96.50,Bodyweight,2,Muscle & Sculpting,Cardio_Core,100.0,47.5,140.0
8,2703,M,31.5,102.55,Barbell,2,Powerlifting,Best3DeadliftKg,232.5,160.0,260.0
9,1472,F,35.0,53.60,Dumbbell,0,Muscle & Sculpting,Best3DeadliftKg,80.0,50.0,92.5
10,206,M,32.0,94.10,Machine,2,Athletics,Cardio_Core,205.0,145.0,250.0
11,249,M,32.0,107.80,Bodyweight,0,Powerlifting,Cardio_Core,230.0,175.0,250.0
12,1592,M,43.5,98.75,Bodyweight,2,Bodybuilding,Best3BenchKg,210.0,162.5,260.0
13,495,M,41.0,100.20,Machine,0,Powerlifting,Best3DeadliftKg,190.0,120.0,200.0
14,2479,F,31.0,55.60,Machine,0,Bodybuilding,Best3DeadliftKg,100.0,55.0,145.0
15,2140,M,33.0,72.50,Bodyweight,0,Powerbuilding,Best3DeadliftKg,140.0,135.0,240.0
16,2302,M,18.0,81.50,Machine,1,Bodybuilding,Best3DeadliftKg,192.5,115.0,210.0
17,2408,M,29.0,86.50,Dumbbell,2,Powerlifting,Best3DeadliftKg,175.0,132.5,192.5
18,2542,M,38.0,90.00,Machine,0,Bodybuilding,Best3BenchKg,212.5,127.5,250.0
19,2806,M,37.0,88.00,Barbell,0,Powerbuilding,Cardio_Core,190.0,190.0,200.0

In [4]:
# Нам нужно вытащить Exercise_Name из твоего маппинга по exercise_id
# Используем merge, чтобы точно сопоставить названия с ID
df_final_reg = df_final_reg.merge(
    df_mapping[['exercise_id', 'Exercise_Name']], 
    on='exercise_id', 
    how='left'
)

# Переставим колонки, чтобы название было сразу после ID для удобства
cols = ['exercise_id', 'Exercise_Name'] + [c for c in df_final_reg.columns if c not in ['exercise_id', 'Exercise_Name']]
df_final_reg = df_final_reg[cols]

print(f"Теперь таблица 'говорящая'. Размер: {df_final_reg.shape}")
display(df_final_reg.head())

Теперь таблица 'говорящая'. Размер: (45239, 12)

,exercise_id,Exercise_Name,Sex,Age,BodyweightKg,eq_clean,level_idx,goal_clean,Base_Lift,Best3SquatKg,Best3BenchKg,Best3DeadliftKg
0,1546,Low Cable Fly,F,33.0,58.30,Machine,3,Powerbuilding,Best3BenchKg,80.0,60.0,107.5
1,1440,Lat Pullover,F,43.0,73.10,Machine,0,Bodybuilding,Best3DeadliftKg,105.0,67.5,110.0
2,2733,Super ROM Overhead Cable Row,M,15.5,67.40,Machine,0,Athletics,Best3DeadliftKg,100.0,62.5,105.0
3,2731,Super ROM Lateral Dumbbell Raise,M,35.0,66.65,Dumbbell,0,Athletics,Best3DeadliftKg,137.5,122.5,170.0
4,1075,Half Kneeling Landmine Press,M,26.5,72.45,Barbell,1,Athletics,Best3BenchKg,90.0,50.0,125.0

In [5]:
import pandas as pd
import numpy as np

# # 1. ФУНКЦИЯ ИНТЕГРИРОВАННОЙ ТРЕНЕРСКОЙ ЛОГИКИ
# def calculate_pro_stats_integrated(row):
#     # --- БАЗОВАЯ ЛОГИКА ЦЕЛЕЙ (Повторы и Интенсивность) ---
#     goal_logic = {
#         'Powerlifting': {'reps': 3, 'int': 0.85},
#         'Bodybuilding': {'reps': 10, 'int': 0.70},
#         'Athletics': {'reps': 12, 'int': 0.60},
#         'Powerbuilding': {'reps': 8, 'int': 0.75},
#         'Muscle & Sculpting': {'reps': 15, 'int': 0.60},
#         'Fitness': {'reps': 12, 'int': 0.65},
#         'Bodyweight Fitness': {'reps': 12, 'int': 0.60}
#     }
#     params = goal_logic.get(row['goal_clean'], {'reps': 10, 'int': 0.70})
    
#     # --- ПОПРАВКИ АТЛЕТА ---
#     level_mult = 0.85 + (row['level_idx'] * 0.05)  # Новичок (0.85) -> Профи (1.0)
#     age_mult = 1.0 - (max(0, row['Age'] - 40) * 0.005) # -0.5% за каждый год после 40
#     sex_rep_adj = 2 if row['Sex'] == 'F' else 0 # Женщинам +2 повтора к базе
#     total_reps = params['reps'] + sex_rep_adj
    
#     # --- БИОМЕХАНИКА УПРАЖНЕНИЯ ---
#     base_ratios = {
#         'Best3SquatKg': 0.75, 
#         'Best3BenchKg': 0.60, 
#         'Best3DeadliftKg': 0.70, 
#         'Cardio_Core': 0.15
#     }
#     ex_ratio = base_ratios.get(row['Base_Lift'], 0.5)
    
#     # --- РАСЧЕТ 1RM ДЛЯ УПРАЖНЕНИЯ ---
#     base_max = row[row['Base_Lift']] if row['Base_Lift'] in row and not pd.isna(row[row['Base_Lift']]) else 0
#     if base_max == 0: return 0.0, 0
    
#     # Коэффициент оборудования
#     eq_mult = {'Barbell': 1.0, 'Dumbbell': 0.85, 'Machine': 1.15, 'Bodyweight': 1.0}.get(row['eq_clean'], 1.0)
    
#     # Абсолютный потенциал в этом упражнении (1RM эквивалент)
#     est_1rm_capacity = base_max * ex_ratio * eq_mult
    
#     # Целевая абсолютная нагрузка (Total Load) с учетом цели, уровня и возраста
#     # Используем формулу Эйли для пересчета 1RM в рабочий вес
#     target_absolute_load = (est_1rm_capacity * params['int'] * level_mult * age_mult) / (1 + total_reps / 30)
    
#     # --- ЛОГИКА ВЕСА ТЕЛА (BODYWEIGHT) ---
#     if row['eq_clean'] == 'Bodyweight':
#         # Сколько % веса тела участвует в движении
#         bw_map = {
#             'pull': 0.95, 'chin': 0.95, 'dip': 0.90, 'push': 0.65, 
#             'squat': 0.70, 'lunge': 0.50, 'leg raise': 0.30, 'plank': 0.50,
#             'skips': 0.60, 'pogo': 0.70, 'march': 0.50, 'crunch': 0.40, 'hip thrust': 0.80
#         }
#         k = 0.8 # дефолт
#         name_lower = str(row['Exercise_Name']).lower()
#         for key, val in bw_map.items():
#             if key in name_lower:
#                 k = val
#                 break
        
#         # Предсказанный доп. вес = Целевая нагрузка - Эффективный вес тела
#         # Если < 0, значит нужна помощь (резина/гравитрон)
#         predicted_weight = target_absolute_load - (row['BodyweightKg'] * k)
#     else:
#         # Для снарядов - это чистый вес на штанге/тренажере
#         predicted_weight = target_absolute_load
        
#     return round(predicted_weight, 1), int(total_reps)

import pandas as pd
import numpy as np

def calculate_pro_stats_integrated(row):
    # --- 1. БАЗОВАЯ ЛОГИКА ЦЕЛЕЙ ---
    goal_logic = {
        'Powerlifting': {'reps': 3, 'int': 0.85},
        'Bodybuilding': {'reps': 10, 'int': 0.70},
        'Athletics': {'reps': 12, 'int': 0.60},
        'Powerbuilding': {'reps': 8, 'int': 0.75},
        'Muscle & Sculpting': {'reps': 15, 'int': 0.60},
        'Fitness': {'reps': 12, 'int': 0.65},
        'Bodyweight Fitness': {'reps': 12, 'int': 0.60}
    }
    params = goal_logic.get(row['goal_clean'], {'reps': 10, 'int': 0.70})
    
    # --- 2. ПОПРАВКИ АТЛЕТА ---
    level_mult = 0.85 + (row['level_idx'] * 0.05) 
    age_mult = 1.0 - (max(0, row['Age'] - 40) * 0.005)
    sex_rep_adj = 2 if row['Sex'] == 'F' else 0
    total_reps = params['reps'] + sex_rep_adj
    
    # --- 3. БИОМЕХАНИКА (ИСПРАВЛЕНО) ---
    base_ratios = {
        'Best3SquatKg': 0.80, 
        'Best3BenchKg': 0.75, 
        'Best3DeadliftKg': 0.85, 
        'Cardio_Core': 0.15
    }
    
    # ПРОВЕРКА: Если название упражнения содержит базу, не режем коэффициент сильно
    ex_name_lower = str(row['Exercise_Name']).lower()
    is_main_lift = any(x in ex_name_lower for x in ['bench press', 'squat', 'deadlift']) and 'dumbbell' not in ex_name_lower
    
    if is_main_lift:
        ex_ratio = 1.0 # База к базе = 100%
    else:
        ex_ratio = base_ratios.get(row['Base_Lift'], 0.5)
    
    # --- 4. РАСЧЕТ 1RM ---
    base_max = row[row['Base_Lift']] if row['Base_Lift'] in row and not pd.isna(row[row['Base_Lift']]) else 0
    if base_max == 0: return 0.0, int(total_reps)
    
    eq_mult = {'Barbell': 1.0, 'Dumbbell': 0.85, 'Machine': 1.10, 'Bodyweight': 1.0}.get(row['eq_clean'], 1.0)
    
    # Эквивалентный 1RM для конкретного упражнения
    est_1rm_capacity = base_max * ex_ratio * eq_mult
    
    # --- 5. РАБОЧИЙ ВЕС (ИСПРАВЛЕНО) ---
    # УБРАЛИ деление на (1 + reps/30), так как params['int'] уже учитывает работу на повторы
    predicted_weight = est_1rm_capacity * params['int'] * level_mult * age_mult
    
    # --- 6. ВЕС ТЕЛА (BODYWEIGHT) ---
    if row['eq_clean'] == 'Bodyweight':
        bw_map = {'pull': 0.95, 'push': 0.65, 'squat': 0.70, 'crunch': 0.40, 'hip thrust': 0.80}
        k = 0.8
        for key, val in bw_map.items():
            if key in ex_name_lower:
                k = val
                break
        predicted_weight = predicted_weight - (row['BodyweightKg'] * k)
    
    return round(max(0, predicted_weight), 1), int(total_reps)
# 2. ПОДГОТОВКА И ВЫВОД ТЕСТОВОЙ ВЫБОРКИ
# Список колонок, которые мы хотим видеть для анализа
analysis_cols = [
    'Exercise_Name', 'Sex', 'Age', 'BodyweightKg', 
    'Best3SquatKg', 'Best3BenchKg', 'Best3DeadliftKg', # Силовые в центре внимания
    'goal_clean', 'level_idx', 'Base_Lift', 'eq_clean',
    'predicted_weight', 'target_reps'
]

# Применяем расчет к 100 рандомным строкам
df_sample = df_final_reg.sample(n=100, random_state=42).copy()
res = df_sample.apply(lambda x: calculate_pro_stats_integrated(x), axis=1)
df_sample['predicted_weight'] = [x[0] for x in res]
df_sample['target_reps'] = [x[1] for x in res]

# Выводим результат
display(df_sample[analysis_cols].head(50))
# 2. ПОДГОТОВКА И ВЫВОД ТЕСТОВОЙ ВЫБОРКИ
# Список колонок, которые мы хотим видеть для анализа
analysis_cols = [
    'Exercise_Name', 'Sex', 'Age', 'BodyweightKg', 
    'Best3SquatKg', 'Best3BenchKg', 'Best3DeadliftKg', # Силовые в центре внимания
    'goal_clean', 'level_idx', 'Base_Lift', 'eq_clean',
    'predicted_weight', 'target_reps'
]

# Применяем расчет к 100 рандомным строкам
df_sample = df_final_reg.sample(n=100, random_state=42).copy()
res = df_sample.apply(lambda x: calculate_pro_stats_integrated(x), axis=1)
df_sample['predicted_weight'] = [x[0] for x in res]
df_sample['target_reps'] = [x[1] for x in res]

# Выводим результат
display(df_sample[analysis_cols].head(50))

,Exercise_Name,Sex,Age,BodyweightKg,Best3SquatKg,Best3BenchKg,Best3DeadliftKg,goal_clean,level_idx,Base_Lift,eq_clean,predicted_weight,target_reps
36660,Lying Overhead Tricep Extension (barbell),M,28.5,114.45,170.0,125.0,175.0,Powerbuilding,0,Best3BenchKg,Machine,65.7,8
24321,Speed Bench Press,M,39.5,103.45,300.0,175.0,285.0,Powerlifting,0,Cardio_Core,Barbell,0.0,3
3460,Incline Dumbbell Row,M,11.0,59.87,97.5,52.5,115.0,Powerlifting,3,Best3DeadliftKg,Dumbbell,70.6,3
23965,Lying Leg Raise,M,50.0,92.40,150.0,107.5,177.5,Bodybuilding,2,Best3BenchKg,Bodyweight,0.0,10
43126,Straight Leg Deadlift,M,58.0,53.50,95.0,75.0,137.5,Powerlifting,2,Best3DeadliftKg,Barbell,101.0,3
26600,Unilateral Preacher Curl,F,22.5,82.80,145.0,90.0,175.0,Muscle & Sculpting,0,Best3DeadliftKg,Dumbbell,64.5,17
25872,Reverse Grip Pushdown,F,40.0,74.60,147.5,70.0,157.5,Powerbuilding,0,Best3BenchKg,Machine,36.8,10
18619,Calf Press (Leg Press Machine),F,46.5,61.00,85.0,57.5,135.0,Powerlifting,2,Best3SquatKg,Machine,58.4,5
13325,Ring Lat Pull,F,21.5,73.60,125.0,70.0,125.0,Powerbuilding,0,Best3DeadliftKg,Bodyweight,0.0,10
38637,Clamshells With Band,M,17.0,80.40,210.0,127.5,230.0,Muscle & Sculpting,0,Cardio_Core,Bodyweight,0.0,15
38691,Wide Grip Incline Benchpress,F,22.0,56.00,110.0,50.0,135.0,Powerbuilding,0,Best3BenchKg,Barbell,23.9,10
13024,Lying Crucifix Lateral Raise,M,18.5,104.05,227.5,122.5,255.0,Bodyweight Fitness,2,Best3DeadliftKg,Dumbbell,105.0,12
25856,Floating Deadlift,F,43.0,56.50,137.5,60.0,140.0,Powerlifting,3,Best3DeadliftKg,Barbell,117.2,5
39814,RP Hammer Strength Shoulder Press - Plate Loaded,M,28.5,106.00,210.0,140.0,200.0,Bodybuilding,2,Best3DeadliftKg,Machine,124.4,10
40847,Seated Abductor Machine (15-20),M,33.0,71.80,190.0,140.0,225.0,Fitness,2,Best3DeadliftKg,Machine,129.9,12
44411,Oblique QL Side Raise,M,15.5,66.10,105.0,82.5,165.0,Muscle & Sculpting,0,Best3BenchKg,Bodyweight,0.0,15
24446,RP Overhead Triceps Extension,F,29.5,78.35,105.0,52.5,155.0,Bodybuilding,2,Best3BenchKg,Dumbbell,22.3,12
17980,Seated Cable Row (One Arm),M,69.5,91.92,130.0,125.0,165.0,Muscle & Sculpting,0,Best3DeadliftKg,Machine,67.1,15
3104,Seated Or Lying Hamstring Curl (Swap This Out ...,M,20.0,97.98,250.0,137.5,275.0,Bodybuilding,1,Best3DeadliftKg,Machine,162.0,10
34736,Trap Bar Farmers Walk,M,21.5,82.67,250.0,147.5,245.0,Powerbuilding,0,Cardio_Core,Barbell,0.0,8
36817,Lateral Raise (Band),M,22.5,89.78,177.5,110.0,215.0,Bodybuilding,1,Cardio_Core,Dumbbell,0.0,10
16339,Bear Craw Isometric Hold,M,50.5,103.65,190.0,140.0,190.0,Powerbuilding,0,Cardio_Core,Bodyweight,0.0,8
5875,Deficit Romanian Deadlift (Barbell),F,34.0,84.40,117.5,55.0,165.0,Muscle & Sculpting,0,Best3DeadliftKg,Barbell,84.1,17
11661,Unilateral Preacher Curl (Dumbbell) Hammer,F,33.5,83.58,130.0,70.0,135.0,Muscle & Sculpting,0,Best3DeadliftKg,Dumbbell,49.7,17
20728,Dumbbell Swing,M,24.0,107.30,285.0,150.0,310.0,Powerbuilding,0,Best3DeadliftKg,Dumbbell,142.8,8
11832,Skull Crusher (Smith),M,34.5,118.80,282.5,172.5,290.0,Athletics,2,Best3BenchKg,Machine,81.1,12
41672,Reverse Hack Squat,M,48.0,97.90,220.0,145.0,235.0,Athletics,0,Best3SquatKg,Machine,118.5,12
30441,Twisting Bench Crunches,M,49.0,73.70,195.0,115.0,242.5,Powerlifting,1,Cardio_Core,Bodyweight,0.0,3
9501,Reverse Wrist Curl (Cable),M,34.0,59.24,95.0,87.5,167.5,Bodybuilding,2,Best3DeadliftKg,Machine,104.1,10
15959,"Legg Press (12,10,8,6,4)",M,19.5,75.62,170.0,100.0,220.0,Fitness,2,Best3BenchKg,Machine,50.9,12
43353,Light cardio (Treadmill Or Rowing machine),M,16.5,71.50,125.0,85.0,150.0,Bodyweight Fitness,0,Cardio_Core,Machine,0.0,12
15868,Bodyweight Hip Thrust,M,31.5,96.85,197.5,145.0,225.0,Powerbuilding,2,Best3SquatKg,Bodyweight,35.1,8
31659,TRX High Row,M,18.5,109.90,257.5,122.5,247.5,Athletics,2,Best3DeadliftKg,Machine,131.9,12
6969,Unilateral Preacher Curl,F,57.0,72.89,72.5,62.5,100.0,Muscle & Sculpting,0,Best3DeadliftKg,Dumbbell,33.7,17
11947,Z-Sit Shoulder Press,M,21.5,119.79,307.5,190.0,355.0,Muscle & Sculpting,2,Best3BenchKg,Dumbbell,69.0,15
10592,Lateral Raise (Machine),F,40.5,51.63,107.5,72.5,145.0,Bodybuilding,2,Best3DeadliftKg,Machine,89.9,12
37449,Stairmaster,M,25.0,71.20,210.0,145.0,250.0,Muscle & Sculpting,0,Cardio_Core,Bodyweight,0.0,15
10852,High Cable Fly,M,49.5,82.25,190.0,130.0,250.0,Muscle & Sculpting,0,Best3BenchKg,Machine,52.1,15
35965,Landmine Oblique Twist,F,18.5,74.00,97.5,55.0,137.5,Bodybuilding,2,Cardio_Core,Barbell,0.0,12
22952,Preacher Curl(Machine),M,20.0,74.00,160.0,97.5,210.0,Athletics,1,Best3DeadliftKg,Machine,106.0,12
28210,Sled Row,M,17.0,92.00,150.0,125.0,202.5,Athletics,3,Best3DeadliftKg,Machine,113.6,12
39865,Prime Leg Extension,F,24.0,49.80,87.5,45.0,120.0,Bodybuilding,2,Best3SquatKg,Machine,51.2,12
16454,Behind-The-Neck Press (Smith Machine),F,22.5,75.47,117.5,85.0,142.5,Bodybuilding,0,Best3DeadliftKg,Machine,79.3,12
35025,3 Count Pause Bench,F,18.5,67.46,100.0,70.0,125.0,Fitness,2,Best3BenchKg,Barbell,32.4,14
21763,Seated Or Lying Hamstring Curl (Swap This Out ...,F,21.0,82.00,125.0,52.5,132.5,Bodybuilding,1,Best3DeadliftKg,Machine,78.0,12
37940,Cable Overhead Extension,M,21.0,98.50,232.5,170.0,250.0,Powerbuilding,0,Best3BenchKg,Machine,89.4,8
1131,Hammer Bar Curl,M,36.0,82.00,210.0,162.5,250.0,Muscle & Sculpting,2,Best3DeadliftKg,Dumbbell,103.0,15
19713,Sled Push,M,20.0,72.80,185.0,125.0,255.0,Bodybuilding,0,Best3BenchKg,Machine,61.4,10
44110,Abs Crunch (Machine),M,21.0,98.60,280.0,210.0,315.0,Bodybuilding,2,Cardio_Core,Machine,0.0,10
35502,Hip Mobilization,M,16.5,71.90,137.5,92.5,140.0,Bodybuilding,0,Best3SquatKg,Bodyweight,7.9,10

,Exercise_Name,Sex,Age,BodyweightKg,Best3SquatKg,Best3BenchKg,Best3DeadliftKg,goal_clean,level_idx,Base_Lift,eq_clean,predicted_weight,target_reps
36660,Lying Overhead Tricep Extension (barbell),M,28.5,114.45,170.0,125.0,175.0,Powerbuilding,0,Best3BenchKg,Machine,65.7,8
24321,Speed Bench Press,M,39.5,103.45,300.0,175.0,285.0,Powerlifting,0,Cardio_Core,Barbell,0.0,3
3460,Incline Dumbbell Row,M,11.0,59.87,97.5,52.5,115.0,Powerlifting,3,Best3DeadliftKg,Dumbbell,70.6,3
23965,Lying Leg Raise,M,50.0,92.40,150.0,107.5,177.5,Bodybuilding,2,Best3BenchKg,Bodyweight,0.0,10
43126,Straight Leg Deadlift,M,58.0,53.50,95.0,75.0,137.5,Powerlifting,2,Best3DeadliftKg,Barbell,101.0,3
26600,Unilateral Preacher Curl,F,22.5,82.80,145.0,90.0,175.0,Muscle & Sculpting,0,Best3DeadliftKg,Dumbbell,64.5,17
25872,Reverse Grip Pushdown,F,40.0,74.60,147.5,70.0,157.5,Powerbuilding,0,Best3BenchKg,Machine,36.8,10
18619,Calf Press (Leg Press Machine),F,46.5,61.00,85.0,57.5,135.0,Powerlifting,2,Best3SquatKg,Machine,58.4,5
13325,Ring Lat Pull,F,21.5,73.60,125.0,70.0,125.0,Powerbuilding,0,Best3DeadliftKg,Bodyweight,0.0,10
38637,Clamshells With Band,M,17.0,80.40,210.0,127.5,230.0,Muscle & Sculpting,0,Cardio_Core,Bodyweight,0.0,15
38691,Wide Grip Incline Benchpress,F,22.0,56.00,110.0,50.0,135.0,Powerbuilding,0,Best3BenchKg,Barbell,23.9,10
13024,Lying Crucifix Lateral Raise,M,18.5,104.05,227.5,122.5,255.0,Bodyweight Fitness,2,Best3DeadliftKg,Dumbbell,105.0,12
25856,Floating Deadlift,F,43.0,56.50,137.5,60.0,140.0,Powerlifting,3,Best3DeadliftKg,Barbell,117.2,5
39814,RP Hammer Strength Shoulder Press - Plate Loaded,M,28.5,106.00,210.0,140.0,200.0,Bodybuilding,2,Best3DeadliftKg,Machine,124.4,10
40847,Seated Abductor Machine (15-20),M,33.0,71.80,190.0,140.0,225.0,Fitness,2,Best3DeadliftKg,Machine,129.9,12
44411,Oblique QL Side Raise,M,15.5,66.10,105.0,82.5,165.0,Muscle & Sculpting,0,Best3BenchKg,Bodyweight,0.0,15
24446,RP Overhead Triceps Extension,F,29.5,78.35,105.0,52.5,155.0,Bodybuilding,2,Best3BenchKg,Dumbbell,22.3,12
17980,Seated Cable Row (One Arm),M,69.5,91.92,130.0,125.0,165.0,Muscle & Sculpting,0,Best3DeadliftKg,Machine,67.1,15
3104,Seated Or Lying Hamstring Curl (Swap This Out ...,M,20.0,97.98,250.0,137.5,275.0,Bodybuilding,1,Best3DeadliftKg,Machine,162.0,10
34736,Trap Bar Farmers Walk,M,21.5,82.67,250.0,147.5,245.0,Powerbuilding,0,Cardio_Core,Barbell,0.0,8
36817,Lateral Raise (Band),M,22.5,89.78,177.5,110.0,215.0,Bodybuilding,1,Cardio_Core,Dumbbell,0.0,10
16339,Bear Craw Isometric Hold,M,50.5,103.65,190.0,140.0,190.0,Powerbuilding,0,Cardio_Core,Bodyweight,0.0,8
5875,Deficit Romanian Deadlift (Barbell),F,34.0,84.40,117.5,55.0,165.0,Muscle & Sculpting,0,Best3DeadliftKg,Barbell,84.1,17
11661,Unilateral Preacher Curl (Dumbbell) Hammer,F,33.5,83.58,130.0,70.0,135.0,Muscle & Sculpting,0,Best3DeadliftKg,Dumbbell,49.7,17
20728,Dumbbell Swing,M,24.0,107.30,285.0,150.0,310.0,Powerbuilding,0,Best3DeadliftKg,Dumbbell,142.8,8
11832,Skull Crusher (Smith),M,34.5,118.80,282.5,172.5,290.0,Athletics,2,Best3BenchKg,Machine,81.1,12
41672,Reverse Hack Squat,M,48.0,97.90,220.0,145.0,235.0,Athletics,0,Best3SquatKg,Machine,118.5,12
30441,Twisting Bench Crunches,M,49.0,73.70,195.0,115.0,242.5,Powerlifting,1,Cardio_Core,Bodyweight,0.0,3
9501,Reverse Wrist Curl (Cable),M,34.0,59.24,95.0,87.5,167.5,Bodybuilding,2,Best3DeadliftKg,Machine,104.1,10
15959,"Legg Press (12,10,8,6,4)",M,19.5,75.62,170.0,100.0,220.0,Fitness,2,Best3BenchKg,Machine,50.9,12
43353,Light cardio (Treadmill Or Rowing machine),M,16.5,71.50,125.0,85.0,150.0,Bodyweight Fitness,0,Cardio_Core,Machine,0.0,12
15868,Bodyweight Hip Thrust,M,31.5,96.85,197.5,145.0,225.0,Powerbuilding,2,Best3SquatKg,Bodyweight,35.1,8
31659,TRX High Row,M,18.5,109.90,257.5,122.5,247.5,Athletics,2,Best3DeadliftKg,Machine,131.9,12
6969,Unilateral Preacher Curl,F,57.0,72.89,72.5,62.5,100.0,Muscle & Sculpting,0,Best3DeadliftKg,Dumbbell,33.7,17
11947,Z-Sit Shoulder Press,M,21.5,119.79,307.5,190.0,355.0,Muscle & Sculpting,2,Best3BenchKg,Dumbbell,69.0,15
10592,Lateral Raise (Machine),F,40.5,51.63,107.5,72.5,145.0,Bodybuilding,2,Best3DeadliftKg,Machine,89.9,12
37449,Stairmaster,M,25.0,71.20,210.0,145.0,250.0,Muscle & Sculpting,0,Cardio_Core,Bodyweight,0.0,15
10852,High Cable Fly,M,49.5,82.25,190.0,130.0,250.0,Muscle & Sculpting,0,Best3BenchKg,Machine,52.1,15
35965,Landmine Oblique Twist,F,18.5,74.00,97.5,55.0,137.5,Bodybuilding,2,Cardio_Core,Barbell,0.0,12
22952,Preacher Curl(Machine),M,20.0,74.00,160.0,97.5,210.0,Athletics,1,Best3DeadliftKg,Machine,106.0,12
28210,Sled Row,M,17.0,92.00,150.0,125.0,202.5,Athletics,3,Best3DeadliftKg,Machine,113.6,12
39865,Prime Leg Extension,F,24.0,49.80,87.5,45.0,120.0,Bodybuilding,2,Best3SquatKg,Machine,51.2,12
16454,Behind-The-Neck Press (Smith Machine),F,22.5,75.47,117.5,85.0,142.5,Bodybuilding,0,Best3DeadliftKg,Machine,79.3,12
35025,3 Count Pause Bench,F,18.5,67.46,100.0,70.0,125.0,Fitness,2,Best3BenchKg,Barbell,32.4,14
21763,Seated Or Lying Hamstring Curl (Swap This Out ...,F,21.0,82.00,125.0,52.5,132.5,Bodybuilding,1,Best3DeadliftKg,Machine,78.0,12
37940,Cable Overhead Extension,M,21.0,98.50,232.5,170.0,250.0,Powerbuilding,0,Best3BenchKg,Machine,89.4,8
1131,Hammer Bar Curl,M,36.0,82.00,210.0,162.5,250.0,Muscle & Sculpting,2,Best3DeadliftKg,Dumbbell,103.0,15
19713,Sled Push,M,20.0,72.80,185.0,125.0,255.0,Bodybuilding,0,Best3BenchKg,Machine,61.4,10
44110,Abs Crunch (Machine),M,21.0,98.60,280.0,210.0,315.0,Bodybuilding,2,Cardio_Core,Machine,0.0,10
35502,Hip Mobilization,M,16.5,71.90,137.5,92.5,140.0,Bodybuilding,0,Best3SquatKg,Bodyweight,7.9,10

In [6]:
import os

# Применяем расчет ко ВСЕМУ датасету
print(f"🔄 Обработка {len(df_final_reg)} строк. Пожалуйста, подождите...")

# Применяем функцию и разделяем результат на две колонки
results_all = df_final_reg.apply(lambda x: calculate_pro_stats_integrated(x), axis=1)
df_final_reg['predicted_weight'] = [x[0] for x in results_all]
df_final_reg['target_reps'] = [x[1] for x in results_all]

# Формируем имя файла
output_filename = "./datasets/gym_dataset_with_targets_FINAL.csv"

# Сохраняем на диск
df_final_reg.to_csv(output_filename, index=False)

print(f"✅ Готово! Датасет сохранен как: {output_filename}")
print(f"📊 Средний предсказанный вес: {df_final_reg['predicted_weight'].mean():.2f} кг")

🔄 Обработка 45239 строк. Пожалуйста, подождите...
✅ Готово! Датасет сохранен как: ./datasets/gym_dataset_with_targets_FINAL.csv
📊 Средний предсказанный вес: 63.55 кг